facultypage/category/urls.py
from django.conf.urls import url
from . import views

app_name = 'category'

urlpatterns = [
    #url(r'^$', views.index, name='index'),
    url(r'^email/$', views.email, name='email'),
    url(r'^about/$', views.about, name='about'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^home/$', views.home, name='home'),
    url(r'^publications/$', views.publications, name='publications'),
    url(r'^deleteteaching/(?P<pk>[0-9]+)/$', views.deleteteaching, name='deleteteaching'),
    url(r'^deleteedu/(?P<pk>[0-9]+)/$', views.deleteedu, name='deleteedu'),
    url(r'^deleteexperience/(?P<pk>[0-9]+)/$', views.deleteexperience, name='deleteexperience'),
    # url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    # url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
     url(r'^createabout/$', views.createabout, name='createabout'),
    url(r'^editabout/$', views.editabout, name='editabout'),
    url(r'^aboutto/(?P<user_name>.*)/$',views.aboutto,name='aboutto'),
    url(r'^todolist/$', views.todolist, name='todolist'),
    url(r'^createeducation/$', views.createeducation, name='createeducation'),
    url(r'^education/$', views.education, name='education'),
    url(r'^teaching/$', views.teaching, name='teaching'),
    url(r'^addteaching',views.addteaching,name="addteaching"),
    url(r'^createexperience/$', views.createexperience, name='createeducation'),
    url(r'^createtodo/$', views.createtodo, name='createtodo'),
    url(r'^experience/$', views.experience, name='education'),
    url(r'^deletetodo/(?P<pk>[0-9]+)/$', views.deletetodo, name='deletetodo'),
    # url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    # url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    # url(r'^(?P<album_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),
    # url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
]

facultypage/facultypage/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('category.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

facultypage/category/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
# Create your models here.


class About(models.Model):
    user = models.ForeignKey(User, default=1)
    name=models.CharField(max_length=200)
    position = models.CharField(max_length=250)
    dept = models.CharField(max_length=500)
    college = models.CharField(max_length=100)
    image = models.FileField()
    intro = models.CharField(max_length=1000)
    email = models.EmailField(max_length=100)
    telephone = models.IntegerField()
    officeaddress = models.CharField(max_length=500)

    def __str__(self):
        return self.name


class Edu(models.Model):
    user = models.ForeignKey(User, default=1)
    institute=models.CharField(max_length=100)
    degree=models.CharField(max_length=100)
    timeperiod=models.CharField(max_length=100)

    def __str__(self):
        return self.institute

class Teaching(models.Model):
    user=models.ForeignKey(User,default=1)
    course=models.CharField(max_length=100)
    currentorpast=models.CharField(max_length=10)

    def __str__(self):
        return self.course

class Experience(models.Model):
    user = models.ForeignKey(User, default=1)
    position=models.CharField(max_length=100)
    institute=models.CharField(max_length=100)
    timeperiod=models.CharField(max_length=100)

    def __str__(self):
        return self.position

class Todolist(models.Model):
    class Meta:
        ordering = ['month','date']
    user=models.ForeignKey(User, default=1)
    reminder=models.CharField(max_length=200)
    date=models.IntegerField(max_length=2)
    month=models.IntegerField(max_length=2)

facultypage/category/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import About,Edu,Teaching,Experience,Todolist
from snowpenguin.django.recaptcha2.fields import ReCaptchaField
from snowpenguin.django.recaptcha2.widgets import ReCaptchaWidget



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','email','password']


class AboutForm(forms.ModelForm):

    class Meta:
        model = About
        fields = ['name','position', 'dept', 'college','image', 'intro','email','telephone','officeaddress']

class EduForm(forms.ModelForm):

    class Meta:
        model = Edu
        fields = [ 'institute', 'degree', 'timeperiod']

class ExperienceForm(forms.ModelForm):

    class Meta:
        model = Experience
        fields = [ 'position', 'institute', 'timeperiod']

class TeachingForm(forms.ModelForm):

    class Meta:
        model = Teaching
        fields = ['course','currentorpast']

class TodolistForm(forms.ModelForm):

    class Meta:
        model = Todolist
        fields = ['reminder','date','month']

facultypage/category/views.py
from django.shortcuts import render

# Create your views here.

from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse,HttpResponse
from .forms import UserForm, AboutForm, EduForm,TeachingForm,ExperienceForm,TodolistForm
from django.shortcuts import render,redirect, get_object_or_404
from django.db.models import Q
from .models import About,Edu,Teaching,Experience,Todolist
from .new import fetch,name1
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

def email(request):
    f = open("category/templates/test.txt","r")
    myList = []
    for line in f:
        myList.append(line)
    l = myList[3].split('"')[1::2];
    print(l[0])
    qs = About.objects.get(user=request.user)
    qs.position=l[0]
    qs.save()
    f.close()
    return redirect('/about/')

def publications(request):
    user = request.session.get('infoo')
    info=get_object_or_404(About,name=user)
    zi=name1(user)
    fi=fetch(user,zi)
    # if not fi:
    #     return render(request,'category/index.html',{'info':info})
    # else:
    return render(request,'category/publications.html',{'fi':fi,'info':info})

def home(request):
    info=About.objects.all()
    return render(request,'category/home.html',{'info' :info})

def todolist(request):
    user = request.session.get('infoo')
    infoo = get_object_or_404(About, name=user)
    info=Todolist.objects.filter(user=request.user)
    return render(request,'category/todo.html',{'info':info,'img':infoo})


def about(request):
    if request.user.is_authenticated():
        info=About.objects.get(user=request.user)
        request.session['infoo'] = info.name
        return render(request, 'category/index.html',{'info':info})
    else:
        return redirect('/login_user/')



def education(request):
    user = request.session.get('infoo')
    info=get_object_or_404(About,name=user)
    eduinfo=Edu.objects.filter(user=info.user)
    return render(request, 'category/education.html', {'info': eduinfo,'img':info})

def experience(request):
    user = request.session.get('infoo')
    info=get_object_or_404(About,name=user)
    eduinfo=Experience.objects.filter(user=info.user)
    return render(request, 'category/experience.html', {'info': eduinfo,'img':info})

def teaching(request):
    user = request.session.get('infoo')
    info=get_object_or_404(About,name=user)
    teachinginfo2=Teaching.objects.filter(user=info.user)
    if not teachinginfo2:
         return render(request, 'category/teaching.html', {'current': teachinginfo2, 'past': teachinginfo2, 'img': info})
    else:
        current = Teaching.objects.filter(user=info.user).filter(currentorpast="Current")
        past = Teaching.objects.filter(user=info.user).filter(currentorpast="Past")
        #teachinginfo = get_object_or_404(Teaching, user=info.user)
        #current=teachinginfo.objects.filter(currentorpast="Current")
        #past=teachinginfo.objects.filter(currentorpast="Past")
        return render(request, 'category/teaching.html', {'current': current,'past': past, 'img': info})

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'category/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/about/')
            else:
                return render(request, 'category/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'category/login.html', {'error_message': 'Invalid login'})
    return render(request, 'category/login.html')


def register(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        # form.email = request.POST['Email']
        # form.password = request.POST['password']
        # form.username = request.POST['username']
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    #info = About.objects.filter(user=request.user)
                    return redirect('/createabout/')
    return render(request, 'category/registerform.html')

def createabout(request):
    if not request.user.is_authenticated():
        return render(request, 'category/login.html')
    else:
        form = AboutForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            info = form.save(commit=False)
            info.user = request.user
            info.image = request.FILES['image']
            file_type = info.image.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'info': info,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'category/aboutform.html', context)
            info.save()
            return redirect('/about/')
        context = {
            "form": form,
        }
        return render(request, 'category/aboutform.html', context)

def createtodo(request):
    if not request.user.is_authenticated():
        return render(request, 'category/login.html')
    else:
        form = TodolistForm(request.POST or None)
        if form.is_valid():
            info = form.save(commit=False)
            info.user = request.user
            info.save()
            return redirect('/todolist/')
        context = {

            "form": form,
        }
        return render(request, 'category/register.html', context)

def createeducation(request):
    if not request.user.is_authenticated():
        return render(request, 'category/login.html')
    else:
        form = EduForm(request.POST or None)
        if form.is_valid():
            info = form.save(commit=False)
            info.user = request.user
            info.save()
            return redirect('/education/')
        context = {
            "form": form,
        }
        return render(request, 'category/register.html', context)

def createexperience(request):
    if not request.user.is_authenticated():
        return render(request, 'category/login.html')
    else:
        form = ExperienceForm(request.POST or None)
        if form.is_valid():
            info = form.save(commit=False)
            info.user = request.user
            info.save()
            return redirect('/experience/')
        context = {
            "form": form,
        }
        return render(request, 'category/register.html', context)


def addteaching(request):
    if not request.user.is_authenticated():
        return render(request, 'category/login.html')
    else:
        form = TeachingForm(request.POST or None)
        if form.is_valid():
            info = form.save(commit=False)
            info.user = request.user
            info.save()
            return redirect('/teaching/')
        context = {
            "form": form,
        }
        return render(request, 'category/register.html', context)

def editabout(request):
    info = get_object_or_404(About, user=request.user)
    if request.method == "POST":
        form = AboutForm(request.POST or None, request.FILES or None, instance=info)
        if form.is_valid():
            info = form.save(commit=False)
            info.user = request.user
            info.save()
            return redirect('/about/')
    else:
        form = AboutForm(instance=info)
    return render(request, 'category/aboutform.html', {'form': form})

# def editeducation(request):
#     user = request.session.get('infoo')
#     info = get_object_or_404(About, name=user)
#     eduinfo = get_object_or_404(Edu,user=info.user)
#     if request.method == "POST":
#         form = EduForm(request.POST or None, instance=eduinfo)
#         if form.is_valid():
#             eduinfo = form.save(commit=False)
#             eduinfo.user = request.user
#             eduinfo.save()
#             return redirect('/education/')
#     else:
#         form = EduForm(instance=eduinfo)
#     return render(request, 'category/register.html', {'form': form})

def aboutto(request,user_name):
    infoo=get_object_or_404(About,name=user_name)
    request.session['infoo'] = infoo.name
    return render(request, 'category/index.html', {'info': infoo})

def deleteedu(request,pk):
    instance = Edu.objects.get(id=pk)
    instance.delete()
    return redirect('/education/')

def deleteexperience(request,pk):
    instance = Experience.objects.get(id=pk)
    instance.delete()
    return redirect('/experience/')

def deleteteaching(request,pk):
    instance = Teaching.objects.get(id=pk)
    instance.delete()
    return redirect('/teaching/')

def deletetodo(request,pk):
    instance = Todolist.objects.get(id=pk)
    instance.delete()
    return redirect('/todolist/')

facultypage/category/templates/category/aboutform2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

</head>
<body>
<br><br>
<div class="container" id="con" >
<form class="form-horizontal" role="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
  <div class="form-group row" >
    <label  class="col-sm-2 col-form-label">Name</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="name" placeholder="Your name">
    </div>
  </div>
    <div class="form-group row" >
    <label  class="col-sm-2 col-form-label">Positoin</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="position" placeholder="Your name">
    </div>
  </div>


    <div class="form-group row" >
    <label  class="col-sm-2 col-form-label">Department</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="dept" placeholder="Your name">
    </div>

  </div>
   <div class="form-group row" >
    <label  class="col-sm-2 col-form-label">College</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="college" placeholder="Your name">
    </div>
  </div>
   <div class="form-group row" >
    <label  class="col-sm-2 col-form-label">Image</label>
    <div class="col-sm-10">
      <input type="file" class="form-control" name="image" placeholder="Your name">
    </div>
  </div>

    <div class="form-group row" >
    <label  class="col-sm-2 col-form-label">Intro</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="intro" placeholder="Your name">
    </div>
  </div>
    <div class="form-group row" >
    <label  class="col-sm-2 col-form-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" name="email" placeholder="Your name">
    </div>
  </div>

    <div class="form-group row" >
    <label  class="col-sm-2 col-form-label">Office</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" name="officeaddress" placeholder="Your name">
    </div>
  </div>
<div class="form-group row" >
    <label  class="col-sm-2 col-form-label">Telephone</label>
    <div class="col-sm-10">
      <input type="number" class="form-control" name="telephone" placeholder="Your name">
    </div>
  </div>


  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
</form>
</div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

facultypage/category/templates/category/home.html
<html>
<head>
	<title>
		Home Page
	</title>
	 <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <style type="text/css">
    	#cards{
    		float:left;
    		margin:20px;
    	}
    	#cardimage{
    		max-height: 250px;
    		height:250px;
    	}
        #card1{
            /*float: right;*/
        }
    	body {
    		/*background-image: url("http://eskipaper.com/images/orange-light-background-1.jpg");*/
    		background-repeat: no-repeat;
    	}
	</style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div align="right">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <div id="aling">
     <a href="/login_user/"> <button class="btn btn-outline-success my-2 my-sm-0 " type="submit"  align="right">Login</button></a>
      <a href="/register/"><button class="btn btn-outline-success my-2 my-sm-0" type="submit"  action="/register/" align="right">Register</button></a>
     </div>
  </div>
  </div>
</nav>
<div class="container">

{%  for field in info %}
<a href="/aboutto/{{field.name}}/">
<div id="card1">
    <div class="w3-card-4 w3-margin" id="cards" style="width:30%">
        <div class="w3-display-container w3-text-white">
            <img class="card-img-top" src="{{ field.image.url }}" alt="Card image cap" id="cardimage">
            <div class="w3-xlarge w3-display-bottomleft w3-padding">{{ field.name }}</div>
        </div>
        <div class="w3-row">
            <div class="card-block" align="center">
            <br/>
            <div class="w3-container w3-center">
                <p>{{ field.position }}</p>
            </div>
        </div>
    </div>
</div>
</a>

{%  endfor %}
</div>
 <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

facultypage/category/templates/category/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html >
<head>

  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  <title>Login</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
<style type="text/css">
	#login{
		margin-top:100px;
	}
	#mainbody{
		background-color: #FED8B1;
	}
    <script src='https://www.google.com/recaptcha/api.js'></script>
</style>
</head>

<body>
  <body id="mainbody">
<div class="container" id="login">
	<section id="content">
		{% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
            {% endif %}
		<form class="form-horizontal" role="form" action="{% url 'category:login_user'%}" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<h1>Login Form</h1>
			<div>
				<input type="text" placeholder="Username" required="" id="username" name="username"/>
			</div>
			<div>
				<input type="password" placeholder="Password" required="" id="password" name="password"/>
			</div>
            <div class="g-recaptcha" data-sitekey="6LeHpTcUAAAAALTXhAOfpl8xLyJKdOsw_ppm-ltS"></div>
			<div>
				<input type="submit" value="Log in" />
				<a href="{% url 'category:home'  %}">Back to Home</a>
				<a href="{% url 'category:register' %}">Register</a>
			</div>
		</form><!-- form -->
	</section><!-- content -->
</div><!-- container -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

</body>
  
    <script  src=href="{% static 'js/index.js' %}"></script>

</body>
</html>

facultypage/category/templates/category/logindd.html
{% load staticfiles %}
<html>
<head>
      <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>LogIn</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/devicons/css/devicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/resume.min.css' %}">
</head>
<body>


<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'category:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'category:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

</body>
</html>

facultypage/category/templates/category/registerform.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>registerationform</title>
      <link rel="stylesheet" href="{% static 'css/register.css' %}"

</head>

<body>


<form action="{% url 'category:register'%}" method="post">
	{% csrf_token %}
  <h2>Register</h2>
  		<p>
			<label for="Email" class="floatLabel">Username</label>
			<input id="Email" name="username" type="text">
		</p>
		<p>
			<label for="Email" class="floatLabel">Email</label>
			<input id="Email" name="Email" type="text">
		</p>
		<p>
			<label for="password" class="floatLabel">Password</label>
			<input id="password" name="password" type="password">
			<span>Enter a password longer than 8 characters</span>
		</p>
		<p>
			<label for="confirm_password" class="floatLabel">Confirm Password</label>
			<input id="confirm_password" name="confirm_password" type="password">
			<span>Your passwords do not match</span>
		</p>

		<p>
			<input type="submit" value="Create My Account" id="submit">
		</p>

	</form>

  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script  src="{% static 'js/register.js' %}"></script>
</body>
</html>